apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 10m0s
  install:
    timeout 10m0s
  upgrade:
    timeout: 10m0s
  chart:
    spec:
      chart: postgresql
      version: 16.7.27
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      username: fusionauth
      password: changeMeSuperSecret
      database: fusionauth
    primary:
      persistence:
        enabled: false
        size: 10Gi
