apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 10m0s
  install:
    timeout: 10m0s
    remediation:
      retries: 3
  upgrade:
    timeout: 10m0s
    remediation:
      retries: 3

  # Ensure FA only installs after Postgres is healthy
  dependsOn:
    - name: postgres
      namespace: fusionauth

  chart:
    spec:
      chart: fusionauth
      # optionally pin: version: 1.59.1
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system

  values:
    # --- Database config ---
    database:
      protocol: postgresql
      host: postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      user: fusionauth
      password: changeMeSuperSecret

    # --- Use DB search (no Elasticsearch) ---
    search:
      engine: database

    # --- Service/Ingress for Docker provider ---
    service:
      type: NodePort
    ingress:
      enabled: false

