apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Make apps apply after infra (repos)
  dependsOn:
    - name: infra

  # Keep reconciles from timing out while images/pods start
  wait: false
  timeout: 10m0s

